# MERT optimized configuration
# decoder /common/student/courses/MT-5LN711-18/tools/MOSES/ubuntu-16.04/bin/moses
# BLEU 0.202608 on dev /home/yihu2298/zh_back/corpora/eng-djk/dev.tk.lc.clean.eng
# We were before running iteration 6
# finished sön 26 okt 2025 01:16:03 CEST
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/yihu2298/zh_back/models/eng-djk/train/model/phrase-table.gz input-factor=0 output-factor=0
Distortion
KENLM name=LM0 factor=0 path=/home/yihu2298/zh_back/lm/all.blm.djk order=5

# dense weights for feature functions
[weight]

Distortion0= 0.0518155
LM0= 0.122429
WordPenalty0= -0.424957
PhrasePenalty0= -0.236445
TranslationModel0= 0.0745701 0.0165358 0.0212413 0.0520055
UnknownWordPenalty0= 1
