# MERT optimized configuration
# decoder /common/student/courses/MT-5LN711-18/tools/MOSES/ubuntu-16.04/bin/moses
# BLEU 0.199931 on dev /home/yihu2298/zh_back/corpora/eng-djk/dev.tk.lc.clean.eng
# We were before running iteration 4
# finished sön 26 okt 2025 01:10:19 CEST
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/yihu2298/zh_back/models/eng-djk/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
Distortion
KENLM name=LM0 factor=0 path=/home/yihu2298/zh_back/lm/all.blm.djk order=5

# dense weights for feature functions
[weight]

Distortion0= 0.0548258
LM0= 0.132384
WordPenalty0= -0.445867
PhrasePenalty0= -0.196263
TranslationModel0= 0.043968 0.042601 0.0694082 0.0146841
UnknownWordPenalty0= 1
