# MERT optimized configuration
# decoder /common/student/courses/MT-5LN711-18/tools/MOSES/ubuntu-16.04/bin/moses
# BLEU 0.0314644 on dev /home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/corpora/zho-djk/dev.tk.cl.djk
# We were before running iteration 13
# finished tor 23 okt 2025 18:42:24 CEST
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/zhs/tuning/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
Distortion
KENLM name=LM0 factor=0 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/lm/bible.blm.zhs order=5

# dense weights for feature functions
[weight]

Distortion0= 0.0579334
LM0= 0.393204
WordPenalty0= 0.0601482
PhrasePenalty0= 0.240538
TranslationModel0= 0.0845545 0.127658 0.0127795 -0.0231838
UnknownWordPenalty0= 1
