# MERT optimized configuration
# decoder /common/student/courses/MT-5LN711-18/tools/MOSES/ubuntu-16.04/bin/moses
# BLEU 0.025776 on dev /home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/corpora/zho-djk/dev.tk.cl.djk
# We were before running iteration 3
# finished tor 23 okt 2025 18:36:41 CEST
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/zhs/tuning/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
Distortion
KENLM name=LM0 factor=0 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/lm/bible.blm.zhs order=5

# dense weights for feature functions
[weight]

Distortion0= -0.310887
LM0= 0.0644263
WordPenalty0= 0.0369841
PhrasePenalty0= 0.357542
TranslationModel0= 0.00756112 0.124544 0.0958654 0.00219037
UnknownWordPenalty0= 1
