# MERT optimized configuration
# decoder /common/student/courses/MT-5LN711-18/tools/MOSES/ubuntu-16.04/bin/moses
# BLEU 0.0310367 on dev /home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/corpora/zho-djk/dev.tk.cl.djk
# We were before running iteration 8
# finished tor 23 okt 2025 18:39:17 CEST
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/zhs/tuning/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
Distortion
KENLM name=LM0 factor=0 path=/home/yihu2298/5LN718-MT/uu-machine-translation-project/smt_zh/lm/bible.blm.zhs order=5

# dense weights for feature functions
[weight]

Distortion0= 0.0758152
LM0= 0.493071
WordPenalty0= 0.0143493
PhrasePenalty0= 0.0371374
TranslationModel0= 0.295653 0.0344031 0.0361276 -0.0134434
UnknownWordPenalty0= 1
